/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import Conversores.Numeros;
import Documentos.CuerpoDetalle;
import Documentos.Encabezado;
import Documentos.PieDocumento;
import Documentos.ResumenDeSaldo;
import interfaces.Contratable;
import interfaces.Generable;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import objetos.Inquilinos;
import objetos.Propiedades;
import objetos.Recibos;
import objetos.RecibosResumen;
import objetos.Saldos;
import tablas.MiModeloTablaCargaHdr;

/**
 *
 * @author mauro di
 */
public class ListadoDeSaldos extends javax.swing.JDialog {
    private MiModeloTablaCargaHdr mod=new MiModeloTablaCargaHdr();
    public static ArrayList listadoSeleccion;
    public static Integer idPropiedad;
    public static Integer idContrato;
    
    /**
     * Creates new form ListadoDeSaldos
     */
    public ListadoDeSaldos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listadoSeleccion=new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Saldos");
        setModal(true);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Resumen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(mod);
        jScrollPane2.setViewportView(jTable1);

        jButton3.setText("Generar Recibo Comp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Recibo Parcial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cantidad=jTable1.getRowCount();
        Saldos saldo;
        Boolean sel=false;
        Integer id;
        Double ss;
        Double tt;
        Double rr;
        String venc=null;
        for(int i=0; i< cantidad;i++){
            sel=(Boolean) jTable1.getValueAt(i, 0);
            if(sel){
            saldo=new Saldos();
            id=Integer.parseInt(String.valueOf(jTable1.getValueAt(i,1)));
            saldo.setIdResumen(id);
            venc=String.valueOf(jTable1.getValueAt(i,2));
            saldo.setVencimientoString(venc);
            ss=Numeros.ConvertirStringADouble(String.valueOf(jTable1.getValueAt(i,3)));
            saldo.setSaldo(ss);
            rr=Numeros.ConvertirStringADouble(String.valueOf(jTable1.getValueAt(i,4)));
            saldo.setRecargo(rr);
            tt=Numeros.ConvertirStringADouble(String.valueOf(jTable1.getValueAt(i,5)));
            saldo.setTotal(tt);
            listadoSeleccion.add(saldo);
            }
        }
        System.out.println("cantidad elegidos "+listadoSeleccion.size());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(listadoSeleccion.size()==0){
            JOptionPane.showMessageDialog(this,"No se ha seleccionado ningún items");
        }else{
            //aca debo llamar a documento para crear el pdf con el resumen de saldo
            Encabezado encabezado=new Encabezado();
            Inquilinos inquilino=new Inquilinos();
            Propiedades propiedad=new Propiedades();
            Generable gen=new Propiedades();
            propiedad=(Propiedades) gen.Cargar(Saldos.getIdBuscador());
            
            Contratable genI=new Inquilinos();
            //gen.Cargar(WIDTH)
            inquilino=(Inquilinos)genI.CargarDesdePropiedad(propiedad.getId());
            encabezado.setFecha(Inicio.fechaDia);
            encabezado.setNombre(inquilino.getNombre());
            encabezado.setDireccion(inquilino.getDomicilioRef());
            encabezado.setIdComprobante("Resumen de Saldo");
            encabezado.setLocalidad(Inicio.configuracion.getLocalidad());
            encabezado.setNumeroDeCuit(inquilino.getCuit());
            encabezado.setTelefono(inquilino.getTelefono());
            encabezado.setTextoSuperior(Inicio.configuracion.getNombre()+"\n"+Inicio.configuracion.getDireccion());
            encabezado.setMail(inquilino.getMail());
            CuerpoDetalle cuerpo=new CuerpoDetalle();
            cuerpo.setDetalle(listadoSeleccion);
            PieDocumento pie=new PieDocumento(Inicio.configuracion.getNota1());
            
            ResumenDeSaldo resumen=new ResumenDeSaldo(encabezado,cuerpo,pie);
            resumen.start();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Iterator it=listadoSeleccion.listIterator();
        Saldos saldo=new Saldos();
        Double totalGral=0.0;
        String totalElegido="";
        Recibos recibo;
        RecibosResumen resumen;
        Generable gen=new Recibos();
        recibo=new Recibos();
        recibo.setFecha(Inicio.fechaDia);
        recibo.setIdUsuario(Inicio.usuario.getNumeroId());
        recibo.setIdPropiedad(idPropiedad);
        recibo.setIdContrato(idContrato);
        ArrayList listadoSald=new ArrayList();
        while(it.hasNext()){
            saldo=(Saldos)it.next();
            totalGral=totalGral + saldo.getTotal();
            resumen=new RecibosResumen();
            resumen.setDescripcion("Resumen N° "+saldo.getIdResumen()+" monto :"+saldo.getSaldo()+" recargo :"+saldo.getRecargo());
            resumen.setIdResumen(saldo.getIdResumen());
            resumen.setRecargo(saldo.getRecargo());
            resumen.setMonto(saldo.getTotal());
            resumen.setSaldoOriginal(saldo.getSaldo());
            resumen.setSaldo(0.00);
            listadoSald.add(resumen);
        }
        recibo.setMonto(totalGral);
        recibo.setResumenRecibos(listadoSald);
        totalElegido=String.valueOf(JOptionPane.showInputDialog(this,"Ingrese numero a imprimir ","0"));
        recibo.setNumero(Integer.parseInt(totalElegido));
        gen.Alta(recibo);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoDeSaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoDeSaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoDeSaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoDeSaldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoDeSaldos dialog = new ListadoDeSaldos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
