/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfacesGraficas;

import interfaces.Componable;
import interfaces.Generable;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Localidad;
import objetos.Propiedades;
import objetos.Propietarios;
import objetos.Rubro;
import objetos.Usuarios;

/**
 *
 * @author mauro di
 */
public class PropiedadesMod extends javax.swing.JInternalFrame {
    Propiedades propiedad;
    Generable geni;
    public static Propietarios propietario;
    public static Generable gen;
    /**
     * Creates new form PropiedadesMod
     */
    public PropiedadesMod(Propiedades prop) {
        initComponents();
        propiedad=(Propiedades)prop;
        this.jTextField7.setText(propiedad.getDireccion());
        Localidad loc=new Localidad();
        Rubro rub=new Rubro();
        Generable lG=new Localidad();
        Generable lR=new Rubro();
        Iterator ir=lG.Listar().listIterator();
        int locPos=0;
        int sel=0;
        while(ir.hasNext()){
            loc=(Localidad)ir.next();
            ((DefaultListModel)this.jList2.getModel()).addElement(loc.getDescripcion());
            locPos++;
            try{
            if(propiedad.getLocalidad().equals(loc.getDescripcion())){
                this.jList2.setSelectedValue(loc.getDescripcion(),true);
                //this.jList2.setSelectedIndex(locPos);
                System.out.println("elemento seleccionado "+locPos);
            }
            }catch(java.lang.NullPointerException ee){
                
            }
        }
        Iterator iG=lR.Listar().listIterator();
        while(iG.hasNext()){
            rub=(Rubro)iG.next();
            ((DefaultListModel)this.jList3.getModel()).addElement(rub.getDescripcion());
            try{
            if(propiedad.getRubro().getDescripcion().equals(rub.getDescripcion())){
                this.jList3.setSelectedValue(rub.getDescripcion(),true);
                //this.jList2.setSelectedIndex(locPos);
                System.out.println("elemento seleccionado "+locPos);
            }
            }catch(java.lang.NullPointerException ed){
                
            }
        }
        //this.jList3.setSelectedIndex(propiedad.getRubro().getId());
        try{
           this.jLabel2.setText(propiedad.getRubro().getDescripcion());
        }catch(java.lang.NullPointerException ex){
            this.jLabel2.setText("CATEGORIA NO ASIGNADA");
        }
        try{
           this.jLabel1.setText(propiedad.getLocalidad());
        }catch(java.lang.NullPointerException ex){
            this.jLabel1.setText("LOCALIDAD NO ASIGNADA");
        }
        this.jTextField7.requestFocus();
        this.jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("MODIFICACION DE PROPIEDADES");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Propiedad"));

        jLabel8.setText("Direccion :");

        jLabel9.setText("Localidad :");

        jLabel10.setText("Categoría :");

        jList2.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jList3);

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Seleccionar Propietario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jButton1.setText("Propietario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton1)
                .addContainerGap(241, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //propiedad=new Propiedades();
        geni=new Propiedades();
        propiedad.setUsuario(Inicio.usuario.getNumeroId());
        propiedad.setLocalidad(String.valueOf(this.jList2.getSelectedValue()));
        Generable rub=new Rubro();
        int pos=this.jList3.getSelectedIndex();
        pos++;
        System.out.println("LA POSICION ELEGIDA ES "+pos);
        propiedad.setRubro((Rubro)rub.Cargar(pos));
        propiedad.setDireccion(this.jTextField7.getText());
        propiedad.setPropietario(propietario.getId());
        //geni.Alta(propiedad);
        geni.Modificacion(propiedad);
        //numeroPropiedad=propiedad.getId();
        //propietario.setPropiedad(propiedad);

        //((DefaultListModel)this.jList1.getModel()).addElement(propiedad.getDireccion());
        LimpiarPanel2();
        //this.jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        propietario=new Propietarios();
        Propietarios temporal=new Propietarios();
        ArrayList listadoPp=new ArrayList();
        String[] combL = null;
        Generable gg=new Propietarios();
        listadoPp=gg.Listar();
        Iterator it=listadoPp.listIterator();
        while(it.hasNext()){
            temporal=(Propietarios)it.next();
            combL=new String[]{temporal.getNombre()};
        }
        String posicion=(String) JOptionPane.showInputDialog(this,"Seleccione propietario","Seleccion de propietario",JOptionPane.QUESTION_MESSAGE,null,combL,combL[0]);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
       ArrayList listado=new ArrayList();
        DefaultListModel modelo=new DefaultListModel();
        Componable comp=new Propietarios();
        gen=new Propietarios();
        Propietarios propietarios=new Propietarios();
        listado=gen.Listar();
        Iterator it=listado.listIterator();
        while(it.hasNext()){
            propietarios=(Propietarios)it.next();
            modelo.addElement(propietarios.getNombre());
        }
//modelo=comp.LlenarList(1);
        PropietariosL prop=new PropietariosL();
        PropietariosL.jList1.setModel(modelo);
         prop.setVisible(true);
         PropietariosL.jList1.requestFocus();
        //Propietarios propietario=new Propietarios();
                //Generable gen=new Propietarios();
                int renglon=PropietariosL.jList1.getSelectedIndex();
                System.out.println("renglon "+renglon);
                int numero=renglon;
                propietarios=(Propietarios)listado.get(renglon);
        System.out.println("PROPIETARIO "+propietarios.getNombre());
        propietario=propietarios;
    }//GEN-LAST:event_jButton2ActionPerformed
private void LimpiarPanel2(){
    this.jTextField7.setText("");
    this.jTextField7.requestFocus();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
